src/styles/tailwind.v2.css
src/textField/TextField.tsx
tailwind.config.js

- https://app.asana.com/0/1201386529949743/1201825815636330
- https://3design-ui-4rye4wxlo-3-shake.vercel.app/?path=/story/atom-textfield--outlined
- Placeholderの色の調整
- 各所フォント・テキストサイズ類の指定
- paddingの調整
- TextField / Unit : spacingの調整・右寄せ
- Labelのサイズ・margin等の調整

fix(TextField): デザイン調整 

---

src/chip/Chip.stories.tsx
src/chip/Chip.tsx
src/styles/tailwind.v2.css
tailwind.config.js

- Chipコンポーネントのデザインと実装に差異がある
|before|after|
--- | ---
|<img width="208" alt="スクリーンショット 0004-05-20 20 30 15" src="https://user-images.githubusercontent.com/44659317/169521781-a3d60d86-4087-4a33-9fd6-46b6368f61c7.png">|<img width="269" alt="スクリーンショット 0004-05-20 20 46 54" src="https://user-images.githubusercontent.com/44659317/169521924-53ed0a98-3063-446c-96aa-528e6ca2a532.png">|
colorの追加
|negative|white|
--- | ---
|<img width="176" alt="スクリーンショット 0004-05-24 21 18 00" src="https://user-images.githubusercontent.com/44659317/170032805-3d46cf20-913a-4600-8301-2a5633dc1210.png">|<img width="238" alt="スクリーンショット 0004-05-24 21 14 13" src="https://user-images.githubusercontent.com/44659317/170032843-aa5c1b30-8d1c-4c87-9c06-5c809771edf8.png">|
- colorでnegativeを選択した場合に背景色しか変更されないので現行デザインと合わせた
- …

refactor: Chipコンポーネントのデザイン調整

---

.storybook/preview.js
src/badge/Badge.stories.tsx
src/button/Button.stories.tsx
src/card/Card.stories.tsx
src/checkbox/Checkbox.stories.tsx
src/chip/Chip.stories.tsx
src/divider/Divider.stories.tsx
src/dropzone/Dropzone.stories.tsx
src/icon/Icon.stories.tsx
src/layout/Header.stories.tsx
src/layout/Sidebar.stories.tsx
src/loader/Loader.stories.tsx
src/menu/Menu.stories.tsx
src/modal/Modal.stories.tsx
src/radio/Radio.stories.tsx
src/select/Select.stories.tsx
src/skeleton/Skeleton.stories.tsx
src/spacer/Spacer.stories.tsx
src/stepper/Stepper.stories.tsx
src/switch/Switch.stories.tsx
src/tab/Tabs.stories.tsx
src/table/Table.stories.tsx
src/tag/Tag.stories.tsx
src/textField/TextField.stories.tsx
src/typography/Typography.stories.tsx

- #636 
- 
- Storyの区分をFigmaと揃えた
- 並べ方を変更

fix: Storyの区分をFigmaと揃える

---

src/select/Select.tsx

- #640
- https://3design-ui-git-fix-select-height640-3-shake.vercel.app/?path=/story/atom-select--basic
- Selectの高さが39だったのを44に修正
- iconを `MdExpendMore` を使うように修正

fix: Selectのスタイル修正

---

src/chip/Chip.tsx

- Chipコンポーネントをimportした際、`color`の上書きがdefault以外指定できなかった
|before|after|
--- | ---
|<img width="554" alt="スクリーンショット 0004-06-21 17 30 23" src="https://user-images.githubusercontent.com/44659317/174756642-b8ca7a61-0318-4c18-a2db-3d284e59e8c5.png">|<img width="371" alt="スクリーンショット 0004-06-21 17 31 40" src="https://user-images.githubusercontent.com/44659317/174756714-008bb91a-9e22-4ac8-afa2-487b0caf4ca0.png">|
|<img width="597" alt="スクリーンショット 0004-06-21 17 45 36" src="https://user-images.githubusercontent.com/44659317/174757770-41710d7c-6cac-4e80-9869-5e8ad452089b.png">|<img width="590" alt="スクリーンショット 0004-06-21 17 45 52" src="https://user-images.githubusercontent.com/44659317/174757797-ade48c51-8cfa-41b0-bff9-97fd55b7cdf8.png">|
- `type`の定義をExcludeではなくOmitに変更
- …

fix: Chipコンポーネントでdefault以外のcolorが選択出来ないのを修正

---

src/tab/Tabs.tsx

- Tabのコンポーネントを使用している際にconsole.infoが発火され、devtoolsのconsoleにノイズとなってしまっている
- 
- Tabsコンポーネント内の`console.info`を削除

refactor: remove console.info

---

src/radio/Radio.stories.tsx
src/radio/Radio.tsx
src/radio/RadioGroup.tsx
tailwind.config.js

- #634 
- #646 
- https://3design-dnms90ovd-3-shake.vercel.app/?path=/story/form-radio--base
- Muiのスタイルを3designに修正
- disabled propsが正しく渡されるように修正
Before:
After:

fix: Radioのスタイル修正

---

src/tab/Tab.tsx
src/tab/TabList.tsx
src/tab/TabPanel.tsx
src/tab/Tabs.stories.tsx
src/tab/Tabs.tsx

https://github.com/3-shake/3design-ui/issues/687
https://3design-ui.vercel.app/?path=/story/navigation-tab--default-tab
https://3design-ui-v3-git-feat-tab-3-shake.vercel.app/?path=/story/navigation-tab--default-tab
borderがおかしかったので、修正しました。
変更方法としてはborder ではなく、width/height のデザインに変更したのですが、
そうなるとborder-xxxx ではなく、bg-xxxxx になるので、borderのカラーが変わってしまうのですが、
どうしましょう？
@Qs-F

feat: Tab 実装

---

src/table/Table.stories.tsx
src/table/Table.tsx

- 
- 
-　ソート機能を設定する際に設定したWithが反映されない不具合があった。原因は、`getSortByToggleProps`をStyleに上書きしているためだったので、Styleを最後に展開するようにした。動作確認はStorybookで確認済みのため、おそらくこれが原因だと思われる。

feat: Tableコンポーネントでソート機能設定時にStyleを渡るようにする

---

.changeset/young-dingos-jog.md
packages/3design-ui/src/menu/Menu.tsx

MenuのコンテンツをMenuItemで受け入れられるように、nopadding propsを追加

fix(Menu): nopadding 追加

---

.changeset/chilled-trees-enjoy.md
packages/3design-ui/tailwind.config.base.js

以下tailwindcss デフォルトcontent 対応
* 3design-ui 
* src/**

fix: content turborepo/vite-app 対応 \w tailwindcss.config.base.js

---

.changeset/six-crews-punch.md
packages/eslint-config/src/react.cjs

- Close #900 
- warningが出ていたeslintがreactのversionを特定できない問題を修正
- `Warning: React version not specified in eslint-plugin-react settings. See https://github.com/jsx-eslint/eslint-plugin-react#configuration .`
変更なしのため割愛
-

fix(eslint-config): Reactのversionを検出するように修正

---

.changeset/spicy-rice-whisper.md
packages/for-ui/src/button/Button.stories.tsx
packages/for-ui/src/button/Button.tsx
packages/for-ui/src/drawer/Drawer.tsx

- #866 
- ボタンサイズをlargeとmediumのみに変更
- ストーリーブックからsmall定義されたものをmediumに変更
- ボタンのフォントをboldに変更
| 変更前 | 変更後 |
|   ![screencapture-localhost-6006-2022-12-04-11_54_29](https://user-images.githubusercontent.com/67810971/205472073-50ad4a71-38dc-4301-8621-cf9a181d8f14.png) |    ![screencapture-localhost-6006-2022-12-04-11_56_11](https://user-images.githubusercontent.com/67810971/205472075-889d1ce1-e01a-415d-98ab-66e7f6e88843.png) |
特になし

fix(Button): テキストのサイズダウンに伴うスタイル修正

---

.changeset/friendly-clocks-shout.md
packages/for-ui/src/radio/Radio.tsx
packages/for-ui/tailwind.config.base.js

- #905 
- labelとのgapを8pxから4pxに
- paddingありのRadioを縦横24pxに
- indicator部分のサイズを16pxに
- hover時はborderの太さを変えず色だけ変える
- selectedなときはborderの太さを5pxに
| 変更前 | 変更後 |
|    <img width="1202" alt="スクリーンショット 2022-12-06 7 43 33" src="https://user-images.githubusercontent.com/67810971/205758810-66719380-fdbe-466f-b828-4d1bb33590fa.png">    |   <img width="1208" alt="スクリーンショット 2022-12-06 7 43 20" src="https://user-images.githubusercontent.com/67810971/205758807-14b65e25-2efd-45fc-8fda-b54c31a0f16b.png">     |
- 特にありません

fix(Radio): テキストのサイズダウンに伴うスタイル修正

---

.changeset/wild-plants-applaud.md
packages/for-ui/src/table/Table.tsx

- #910 
- Row Componentが `className` を受け取れるように修正 (fsxの対応後入れるのを忘れていた)
差分がないため割愛
-

fix(Table): Row Componentが `className` propsを受け取れるように修正

---

.changeset/cyan-hats-kiss.md
packages/for-ui/.storybook/main.cjs
packages/for-ui/package.json
yarn.lock

- Close #920 
- MDXのstoryのテーブル等が崩れていたのを修正
- `@mdx-js/react` のv2でtableなどが壊れなくなったらこのPRをrevertしてください
| 変更前 | 変更後 |
|       <img width="1373" alt="image" src="https://user-images.githubusercontent.com/8467289/206685722-1045e632-57e0-4e94-8083-1dc240cbacde.png"> |    <img width="1375" alt="image" src="https://user-images.githubusercontent.com/8467289/206685627-a39612cf-5cd9-4314-b90d-9d84329a2246.png">    |
- 現状overrideするしか方法がなさそうでした [参考](https://github.com/storybookjs/storybook/issues/18094#issuecomment-1217135470)

fix: MDXで書かれたStorybookが崩れていたのを修正

---

.changeset/quick-mangos-impress.md
packages/for-ui/src/switch/Switch.tsx

- #870 
- サイズの調整
toggleの大きさを4remに
p-0.5 にする
横幅は32pxになるように
| 変更前 | 変更後 |
|   <img width="628" alt="スクリーンショット 2022-12-09 6 57 29" src="https://user-images.githubusercontent.com/67810971/206576285-f9dcbd10-09d3-4a3a-bdfa-047f36c0935f.png">     |    <img width="594" alt="スクリーンショット 2022-12-09 6 56 35" src="https://user-images.githubusercontent.com/67810971/206576310-426033d4-fe78-4e36-951d-84365c5e6fcf.png">    |
- toggleのサイズや可動域をかなり無理やり調整した感があります...脱muiした方が管理しやすいかもです👀

fix(Switch): テキストのサイズダウンに伴うスタイル修正 

---

.changeset/witty-spiders-knock.md
packages/for-ui/tailwind.config.base.js

- Close #944
- xlの値を修正 (32px -> 24px)
| 変更前 | 変更後 |
|    <img width="1003" alt="image" src="https://user-images.githubusercontent.com/8467289/208844493-58b7d72b-0858-474b-90c6-110567f5222e.png">    |   <img width="1006" alt="image" src="https://user-images.githubusercontent.com/8467289/208844428-40dbecf8-21e6-4031-8d38-faa6dec44585.png">     |
-

fix: `xl` のサイズを修正

---

.changeset/eleven-onions-argue.md
packages/for-ui/src/checkbox/Checkbox.tsx
packages/for-ui/src/chip/Chip.tsx
packages/for-ui/src/drawer/Drawer.tsx
packages/for-ui/src/dropzone/Dropzone.tsx
packages/for-ui/src/menu/Menu.tsx
packages/for-ui/src/modal/Modal.tsx
packages/for-ui/src/radio/Radio.tsx
packages/for-ui/src/select/Select.tsx
packages/for-ui/src/stepper/Stepper.tsx
packages/for-ui/src/switch/Switch.tsx
packages/for-ui/src/tab/Tabs.tsx
packages/for-ui/src/table/Table.tsx
packages/for-ui/tailwind.config.base.js

- Close #936 
- `className` prop が抜けているコンポーネントに `className` propを追加
- `Select` コンポーネントをforwardRefするように修正
- tailwind.config.base.jsの修正
- `fillColor` → `fill`
| 変更前 | 変更後 |
-

fix: `className` prop が抜けているコンポーネントに `className` propを追加

---

.changeset/nervous-icons-vanish.md
packages/for-ui/src/textArea/TextArea.stories.tsx
packages/for-ui/src/textArea/TextArea.tsx

- Close #956
- helperTextとlabelを追加
- 各サービスで上書きできるよう、ReactNodeを受け取るようにして、文字列以外を受け取るとデフォルトのスタイルでないもので描画できるようにしました
| 変更前 | 変更後 |
|     <img width="1339" alt="image" src="https://user-images.githubusercontent.com/8467289/209755822-ef4f9f3c-33d4-482f-94d1-d68e07b7a9fc.png">   |     <img width="1338" alt="image" src="https://user-images.githubusercontent.com/8467289/209755790-26654727-33ea-43cd-82d2-b9610604cac2.png">   |
-

fix(TextArea): `helperText` と `label` propsを追加

---

.changeset/plenty-pans-sip.md
example/vite-app/src/components/map/index.tsx
packages/for-ui/src/select/Select.tsx
packages/for-ui/src/textField/TextField.stories.tsx
packages/for-ui/src/textField/TextField.tsx

- Close #948 
- `TextField / URL`を実装
- `prefix` propにユーザーが入力しなくても既に入っている値 (例: htttps://github.comなど) を指定することで使えます
- variant と margin propsを削除
| 変更前 | 変更後 |
|   <img width="1373" alt="image" src="https://user-images.githubusercontent.com/8467289/209328485-3e8898ad-e6bc-47ec-ae5d-3f8af883084c.png">     |       <img width="1376" alt="image" src="https://user-images.githubusercontent.com/8467289/209328542-9216e1e3-bd57-4eaa-b226-c01038ed6184.png"> |
-

feat(TextField): `TextField / URL` を実装

---

.changeset/grumpy-suits-retire.md
packages/for-ui/src/select/Select.stories.tsx
packages/for-ui/src/select/Select.tsx
packages/for-ui/src/textField/TextField.stories.tsx
packages/for-ui/src/textField/TextField.tsx

- Close #968 
- TextFieldとSelectに対して、`fullWidth` propsを削除しデフォルトで `w-full` になるように修正
| 変更前 | 変更後 |
-

fix: `fullWidth` props を削除しデフォルトで `w-full` になるように修正

---

.changeset/lucky-rockets-smile.md
packages/for-ui/src/textArea/TextArea.tsx

- Close #966 
- `className` がrootのdivに渡るようになっておらず、width等がうまく変更できていなかったのを修正
- デフォルトで `w-full` になるよう修正
- 間違ったバリデーションを修正 (labelではなくhelperTextが正しい)
| 変更前 | 変更後 |
-

fix(TextArea): classNameをrootのdivに渡るように修正

---

.changeset/hip-seas-wash.md
packages/for-ui/src/badge/Badge.stories.tsx
packages/for-ui/src/badge/Badge.tsx
packages/for-ui/src/badge/ConstantBadge.tsx
packages/for-ui/src/badge/OutlineBadge.tsx
packages/for-ui/src/badge/TextBadge.tsx
packages/for-ui/src/badge/index.tsx

- #908 
- Badgeコンポーネントの新デザイン実装
| 変更前 | 変更後 |
|   <img width="683" alt="スクリーンショット 2022-12-26 21 17 43" src="https://user-images.githubusercontent.com/67810971/209548188-85d46f76-58eb-4882-89fb-2814d0d6ad7e.png">     |     <img width="681" alt="スクリーンショット 2022-12-26 21 17 13" src="https://user-images.githubusercontent.com/67810971/209548144-d8454bc5-073d-4274-9c89-52a87c5b354c.png">   |
- muiベースだと実装厳しそうなのでプロパティだけ引き継ぎました

fix(Badge): Badgeコンポーネントのデザイン実装

---

example/nextjs-app/components/Layout.tsx
example/nextjs-app/package-lock.json
example/nextjs-app/package.json

-
- `@tanstack/react-table` をdevDependenciesに追加した
- Next.jsの13系では`next/link`のLinkコンポーネント使用時に`aタグ`を内包するのが不要になったので削除
- https://nextjs.org/docs/messages/invalid-new-link-with-extra-anchor 
| 変更前 | 変更後 |
|<img width="984" alt="スクリーンショット 0005-01-19 19 06 56" src="https://user-images.githubusercontent.com/44659317/213422279-989c23df-7ec4-43c0-9654-abe34f24a0bc.png">| <img width="560" alt="スクリーンショット 0005-01-19 19 46 18" src="https://user-images.githubusercontent.com/44659317/213422580-80addd8d-031f-499c-9e48-b753e9f084c0.png"> |
-

fix (example) : Next.jsのlatestで起動に失敗していたのを修正

---

.changeset/stale-gifts-brake.md
packages/for-ui/src/table/Table.stories.tsx
packages/for-ui/src/table/Table.tsx

- Close #1008
- `onRowClick` が与えられているときにデフォルトのRowコンポーネントでhoverスタイルを適用するようにした
| 変更前 | 変更後 |
|      <img width="1363" alt="image" src="https://user-images.githubusercontent.com/8467289/213607032-8aa46bdd-ac34-431a-a88e-d03b5e8e0ad1.png">  |     <img width="1364" alt="image" src="https://user-images.githubusercontent.com/8467289/213606989-90e1bc96-4422-4776-bf0a-11c68948500d.png">   |
-

fix(Table): `onRowClick` が与えられているときにhover時のスタイルを適用

---

.changeset/funny-comics-cry.md
packages/for-ui/src/menu/MenuItem.tsx
packages/for-ui/src/select/Select.stories.tsx
packages/for-ui/src/select/Select.tsx
packages/for-ui/src/textField/TextField.tsx

- Close #979 
- Selectを `error` と `helperText` propsに対応させる
- 受け取ったpropsをTextFieldに渡して対応
- TextFieldのlabelをクリックしてもfocusしない問題を修正
- MenuItemをカーソルキーで選択しているときに表示がない問題を修正
| 変更前 | 変更後 |
-

fix(Select): `error` と `helperText` propsに対応

---

packages/for-ui/src/button/Button.tsx

- Close #1024 
- Button コンポーネントを `as` propsを受け取れるように修正
- genericにすることで例えばaタグならhrefを受け取れるように修正
- onClickなどが使った要素に従ってeventの型が変わるように修正
| 変更前 | 変更後 |
-

fix(Button): `as` propsで描画に使う要素を指定できるように修正

---

packages/for-ui/src/button/Button.tsx

Revert "fix(Button): `as` propsで描画に使う要素を指定できるように修正"

---

.changeset/nine-kings-pull.md
packages/for-ui/src/checkbox/Checkbox.stories.tsx
packages/for-ui/src/checkbox/Checkbox.tsx
packages/for-ui/src/checkbox/CheckboxGroup.tsx
packages/for-ui/src/radio/Radio.stories.tsx
packages/for-ui/src/radio/Radio.tsx
packages/for-ui/src/radio/RadioGroup.tsx
packages/for-ui/src/switch/Switch.stories.tsx
packages/for-ui/src/switch/Switch.tsx
packages/for-ui/src/switch/SwitchGroup.tsx
packages/for-ui/src/system/TextDefaultStyler.tsx
packages/for-ui/src/textArea/TextArea.tsx

- Close #1005 
- labelとerrorとhelperTextの仕様を揃える
- label: ReactNodeを受け取り、stringであればデフォルトのスタイルを、ReactElementであればそのまま表示する
- error: booleanにして、エラーメッセージはhelperTextで描画するように揃える
- helperText: ReactNodeを受け取り、stringであればデフォルトのスタイルを、ReactElementであればそのまま表示する
- 上記の仕様のため、TextDefaultStylerというユーティリティコンポーネントを作成
- content propsをReactNodeにして、stringであればdefaultRendererで受け取ったコンポーネントで、ReactNodeであればそのまま描画する
- Checkbox、Radio、Switchのlabel等を改修、forwardRefに改修
- RadioGroup: 受け取ったrefをchildren (Radio) に流すようにする
- これにより、RadioGroupにreact-hook-formのregisterを渡すと個別のRadioに設定しなくても値が取れるようになった ([参考](https://github.com/4-design/for-ui/pull/1038/files#diff-ecea0fc5e105e2cb8f14bfb6bd346514b3ad2eea88387a59fc88c28f9acf027fR140-R153)) 
- CheckboxGroup: 追加
- TextArea: TextDefaultStylerを使うように修正
| 変更前 | 変更後 |
|        | …

fix(Radio, Switch, Checkbox, TextArea): `label`, `error`, `helperText` propsの仕様を揃える

---

.changeset/itchy-avocados-itch.md
packages/for-ui/src/textArea/TextArea.tsx

- Close #1047 
- https://3shake.slack.com/archives/C03L73GNHB2/p1673579874504209
- 不要な `h-auto` 削除
- ~~`onResize` `onResizeCapture` propsがなぜかライブラリからインポートしてきたときだけrequiredになるバグがあるので暫定的に修正~~ FUI側では根本的な対策ができなさそうなので使う側で対処してもらうことにした
- https://github.com/4-design/for-ui/discussions/1051
| 変更前 | 変更後 |
-

fix(TextArea): 自動サイズ調整が効かないバグの修正

---

.changeset/angry-buttons-suffer.md
packages/for-ui/src/skeleton/Skeleton.stories.tsx
packages/for-ui/src/skeleton/Skeleton.tsx

- Close #1011 
- Skelentonがchildrenによるundefinedやstringを返してエラーになっていた部分を修正
- 型的に `as` のキャストで潰されていた部分を修正
- childrenをrequiredにすることもできましたが、もとの実装の意図的にoptioinalでいいのかなと考えoptionalの際もloadingがtrueであればとりあえずskeletonを出すようになっています
- 色を `shade-background-medium-disabled` の正しい色に変更
- アクセシビリティ対応
| 変更前 | 変更後 |
|    <img width="1410" alt="image" src="https://user-images.githubusercontent.com/8467289/219287789-3a18be4b-be9f-4ce5-ae3f-3709ea196b88.png">    |   <img width="1406" alt="image" src="https://user-images.githubusercontent.com/8467289/219287746-3fc19ba4-eefb-4cda-bf39-39368cb95d9d.png">     |
-

fix(Skeleton): 戻り値の不正なパスを修正

---

.changeset/spicy-zoos-enjoy.md
packages/for-ui/src/textField/TextField.stories.tsx
packages/for-ui/src/textField/TextField.tsx

- Close #1009 
- `unitLabel` をより汎用的な `suffix` propsに変更
- suffixとprefixのデザインを最新のものに修正
- 内部のリファクタリング
- errorやhelperTextの仕様を他と揃えたため、必要なくなった部分を落としTextFieldではなくOutlinedInputを使用し少し軽くした
- スタイル周りを見やすく修正
- focus時のスタイルをCSSで記述するように修正
- `icon` propsを導入し、iconを指定しやすくした
| 変更前 | 変更後 |
|   <img width="1409" alt="image" src="https://user-images.githubusercontent.com/8467289/217729699-bcb18894-2d7a-4e8b-8c0b-e6b6da021a18.png">     |     <img width="1410" alt="image" src="https://user-images.githubusercontent.com/8467289/217729755-8bbd6444-05e3-43c1-825b-961cd296c953.png">   |
-

fix(TextField): `suffix` と `icon` propsの追加とprefixとsuffixのデザイン修正

---

.changeset/bright-peaches-fail.md
packages/for-ui/src/textArea/TextArea.stories.tsx
packages/for-ui/src/textArea/TextArea.tsx

- Close #869 
- TextAreaにsize propsを追加
- TextAreaにsize=mediumを追加
- TextAreaのsize=largeのpaddingを最新のものに修正
| 変更前 | 変更後 |
|    新規につきなし    |   <img width="1408" alt="image" src="https://user-images.githubusercontent.com/8467289/221120593-3742ed69-4778-42d3-8316-b217d505c3dc.png">     |
-

fix(TextArea): size propsの追加とsize=mediumの追加

---

.changeset/ten-flies-build.md
packages/for-ui/src/menu/MenuList.tsx
packages/for-ui/src/select/Select.stories.tsx
packages/for-ui/src/select/Select.tsx

- Close #1010 
- Dividerの追加
- オプションがないときの表示を修正
- ulの直下にdivとなってしまっていたので、MenuListにas propsをつけて対応
- 本来なら `noOptionsText` を表示するコンポーネントを作らせてほしいができないのでこの対応になった
| 変更前 | 変更後 |
|    <img width="1409" alt="image" src="https://user-images.githubusercontent.com/8467289/220056753-7d9e3340-16e6-4eff-9e2a-1368e7d52dfe.png">    |   <img width="1407" alt="image" src="https://user-images.githubusercontent.com/8467289/220056675-750cd4ba-dd56-44c5-9c41-fff6ed33ee91.png">     |
- #1044 のあとにコンフリクトをなおして入れます

fix(Select): dividerの追加とオプションが無いときの表示を修正

---

.changeset/dirty-schools-push.md
packages/for-ui/src/menu/index.tsx

- Close #1076 
- exportを忘れていたMenuDividerをexportするように修正
| 変更前 | 変更後 |
-

fix(Menu): MenuDividerをexport

---

.changeset/quiet-maps-rhyme.md
packages/for-ui/src/select/Select.tsx

- Close #1082 
- disabledのときにexpand moreボタンをdisabled色に修正
| 変更前 | 変更後 |
|    <img width="1154" alt="image" src="https://user-images.githubusercontent.com/8467289/222638244-4211d6f1-1445-4469-869f-ed79c55ba57f.png">    |       <img width="1150" alt="image" src="https://user-images.githubusercontent.com/8467289/222638280-01559856-18b2-4e8f-a271-76bb0d700984.png"> |
-

fix(Select): disabledのときにexpand moreボタンをdisabled色に修正

---

.changeset/tasty-camels-talk.md
packages/for-ui/src/textArea/TextArea.tsx
packages/for-ui/src/textField/TextField.stories.tsx
packages/for-ui/src/textField/TextField.tsx

- Close #1101 
- TextField, TextArea: labelをw-fitにしてクリックしてフォーカスになるエリアを文字の上だけに限定
- アクセシビリティ対応の一貫として必須表示のアスタリスクをabbr要素にした
- https://www.w3.org/TR/WCAG20-TECHS/H90.html によると省略形を使うときはページのどこかに `* は必須を示す` という趣旨の文言が必要なため、やはり必須を文字で書いたラベルのほうが好ましい
| 変更前 | 変更後 |
- Selectで同様の問題が解決できていません。内部的にはTextFieldなので問題なさそうなのですが、現在原因特定中です。

fix(TextField, TeatArea): labelのクリックできるエリアを文字の上だけになるよう修正

---

renovate.json

- Close #1125 
- renovate.jsonの`group:allNonMajor`を外した
- アップグレード作業が終わり次第このPRをrevertすると戻せるはずです
| 変更前 | 変更後 |
-

chore: Renovateのgroup:allNonMajorを外す

---

package-lock.json
package.json

- Close #1150 
- enginesにnpm v7以降を指定
- 根拠等は #1150 を参照
| 変更前 | 変更後 |
-

chore: npm v7以降を使うよう制約を追加

---

packages/for-ui/src/button/Button.test.tsx

- Close #1115 
- Buttonのテストを追加
- ラベルが様々なvariantで描画されていること
- クリックするとonClickが呼ばれること
- disabled, loading状態ではクリックされてもonClickが呼ばれないこと
| 変更前 | 変更後 |
-

chore(Button): テストを追加

---

.changeset/modern-donkeys-jump.md
packages/for-ui/src/system/TextDefaultStyler.tsx

- Close #1180 
- ReactElementの型がReactNodeとisValidElementで異なり、TypeScript v5でエラーとなるため修正した
- 参考 https://github.com/microsoft/TypeScript/issues/53178
- anyを使うほかに解消する術がないためコメントを残した
変更なし
| 変更前 | 変更後 |
-

fix(system): ReactNodeとisValidElementのReactElement型の差異を解消

---

.changeset/chilly-rules-juggle.md
packages/for-ui/src/dropzone/Dropzone.tsx
packages/for-ui/src/select/Select.tsx
packages/for-ui/src/stepper/Step.tsx
packages/for-ui/src/stepper/Stepper.tsx
packages/for-ui/src/tab/Tab.tsx
packages/for-ui/src/table/TableCell.tsx

- Close #1228 
- npm run fmt によるTailwind CSSのクラス名の順序のlint警告を解消
| 変更前 | 変更後 |
-

fix: Tailwind CSSのクラス名の順序を修正

---

.changeset/rotten-frogs-lick.md
packages/for-ui/styles/forty.css
packages/for-ui/tailwind.config.base.js

- Close #1223 
- secondary-border-dark-default が抜けていたのを修正
- Figma側も修正
| 変更前 | 変更後 |
-

fix: secondary-border-dark-default が抜けていたのを修正

---

.changeset/sour-buckets-smash.md
package-lock.json
packages/for-ui/package.json

- Close #1112 
- peerDependenciesのreactと@types/reactのバージョンを18以上に修正
| 変更前 | 変更後 |
-

fix: React v17以下のサポートを終了

---

.changeset/dull-cooks-fail.md
packages/for-ui/src/textField/TextField.tsx

- Close #1236 
- TextFieldの入力欄のテキストサイズがMUI由来で16pxになっていたのを修正
| 変更前 | 変更後 |
-

fix(TextField): 入力欄のテキストサイズを修正

---

.changeset/perfect-sloths-remain.md
packages/for-ui/src/select/Select.tsx
packages/for-ui/src/textField/TextField.tsx

- Close #1239 
- multipleの場合のみinputの最小幅を入れた
- multipleの場合は同様の問題が残るが入力できないよりは表示が崩れているほうが良いという判断
| 変更前 | 変更後 |
-

fix(Select): 横幅を縮めたときに表示が崩れるのを修正

---

packages/for-ui/src/textField/TextField.tsx

- Close #1050 
- TextFieldのhelperTextをerrorのときは`aria-errormessage`に、errorではないときは`aria-describedby` に設定した
| 変更前 | 変更後 |
-

fix(TextField): `aria-errormessage` に対応

---

.changeset/proud-nails-heal.md
packages/for-ui/src/textArea/TextArea.tsx

- Close #1247 
- requiredを内部のtextareaに渡るように修正
- helperTextを `aria-errormessage` と `aria-describedby` に対応させた
| 変更前 | 変更後 |
-

fix(TextArea): アクセシビリティ的問題を修正

---

.changeset/mean-bulldogs-smoke.md
example/nextjs-app/package-lock.json
example/nextjs-app/package.json
example/vite-app/package-lock.json
example/vite-app/package.json
package-lock.json
packages/for-ui/package.json
packages/for-ui/src/chip/Chip.tsx
packages/for-ui/src/chip/FullChip.tsx
packages/for-ui/src/chip/LimitedChip.tsx
packages/for-ui/tsconfig.json

- Close #1303 
- TypeScriptをv5.1.3にアップデート
- 明示的な`typeRoots`があると上位のnode_modulesを見に行かないため削除
- `React.FC`の型定義が変更されたことにより`JSX.Element | null`では不十分になったので修正
| 変更前 | 変更後 |
-

fix(deps): TypeScript v5.1.3にアップデート

---

.changeset/long-parrots-check.md
packages/for-ui/src/stepper/Step.tsx
packages/for-ui/src/stepper/Stepper.stories.tsx
packages/for-ui/src/stepper/Stepper.tsx

- Close #1282 
- Close #1265 
- Close #1266 
- Close #1270 
- Close #1271 
- v1.1.0のデザイン改善時に漏れていたStepperのデザイン改善を入れた
- 「入力の終わったもの」と「現在取り組んでいるもの」の見分けがつきにくい問題を解決
- ラベルを後方におくタイプの作成
- Stepperの大きさや色を見直して、デザイン改善後の他のコンポーネントと並べたときに主張が強すぎないように修正
- `alternativeLabel` propを廃止し、`labelPosition` propで置き換え
| 変更前 | 変更後 |
|   <img width="1416" alt="image" src="https://github.com/4-design/for-ui/assets/8467289/b3236591-101a-40e6-ae74-61cd48dbb8d2">     |   <img width="1418" alt="image" src="https://github.com/4-design/for-ui/assets/8467289/6a115950-cfe8-4945-8a84-c2596a49cdaa"> 
| 該当なし | <img width="1417" alt="image" src="https://github.com/4-design/for-ui/assets/8467289/5f868922-bdb2-4b7f-b666-69096eba983d">   |
-

fix(Stepper): デザイン改善

---

.changeset/dull-kangaroos-scream.md
packages/for-ui/src/chip/Chip.tsx
packages/for-ui/src/table/Table.stories.tsx
packages/for-ui/src/table/Table.tsx
packages/for-ui/src/table/TableCell.tsx
packages/for-ui/src/table/TableScroller.tsx

- Close #1292 
- Close #1291 
- Close #1272 
- Close #881 
- 選択可能なTableで不要な文言が出ていたのを修正
- `react-table` を使わないtableのためのスタイルつきコンポーネントを作成 & export
- 並び順を変更できるテーブルのアクセシビリティ向上
- テーブルの高さを固定値にしたときにヘッダを固定表示するように修正
- 最後の行の下線を消す修正
- 並び替えできるヘッダについて、hoverで矢印を表示するように修正
| 変更前 | 変更後 |
|   <img width="1417" alt="image" src="https://github.com/4-design/for-ui/assets/8467289/8de9c64f-4aae-4157-aa7f-7cb44d11dcc7">     |     <img width="1418" alt="image" src="https://github.com/4-design/for-ui/assets/8467289/098b125c-b6cf-4579-8689-d69df83dc3c9">   |
動作確認
https://github.com/4-design/for-ui/assets/8467289/583c82be-f60a-4b51-8699-618a0f7aebf0
| 状態 | スクリーンショット | 修正の意図 |
| -- | -- | -- |
| 高さ固定 (コンテンツよりも低い) | <img width="1176" alt="image" …

fix(Table): 選択可能なTableのバグ修正とヘッダの高さ等を整える修正

---

.changeset/four-spoons-cough.md
package-lock.json
packages/for-ui/src/table/Table.stories.tsx
packages/for-ui/src/table/Table.tsx
packages/for-ui/src/table/TablePagination.tsx

fix(Table): 外部からページを指定できるようにする

---

.changeset/eleven-items-double.md
packages/for-ui/src/table/Table.tsx

- Close #1361 
- Tableのスクロールバーの領域がスクロールが発生しないときも常にpaddingが設定されているのを修正
| 変更前 | 変更後 |
|   <img width="1195" alt="image" src="https://github.com/4-design/for-ui/assets/8467289/5301611a-8adb-4108-b4bf-965a235ca969">     |    <img width="1196" alt="image" src="https://github.com/4-design/for-ui/assets/8467289/9ffbab10-8f18-4823-aeb3-c12216b77b39">    |
-

fix(Table): スクロールバーを常に表示に設定しているときの意図しないpaddingを除去

---

.changeset/six-pillows-work.md
packages/for-ui/src/callout/Callout.tsx

- Close #1383 
- Calloutに `w-full h-fit` を追加
- flex内に置かれたときに意図しないレイアウト崩れを防ぐため
| 変更前 | 変更後 |
-

fix(Callout): レイアウトの修正

---

.changeset/itchy-rice-allow.md
packages/for-ui/src/button/Button.tsx

- Close #1334 
- Buttonのローディングアイコンの色とサイズを修正
| 変更前 | 変更後 |
|    <img width="1496" alt="image" src="https://github.com/4-design/for-ui/assets/8467289/2aa358ab-0497-4671-8af1-466e2fa2880d">    |    <img width="1496" alt="image" src="https://github.com/4-design/for-ui/assets/8467289/7144570e-8629-429a-924e-a479d8b58945">    |
-

fix(Button): ローディングアイコンの色とサイズを修正

---

.changeset/good-ants-cough.md
packages/for-ui/src/button/Button.tsx

- Close #1408 
- `intention=subtle`かつ構造がアイコンのときにアイコンの色をshade-icon-dark-defaultに変更
| 変更前 | 変更後 |
|   <img width="1387" alt="image" src="https://github.com/4-design/for-ui/assets/8467289/870f0451-c329-4bc1-9864-627624559bdf">     |    <img width="1387" alt="image" src="https://github.com/4-design/for-ui/assets/8467289/3b286f3d-d896-49fd-ba2a-dae63c7530fe">    |
| <img width="1386" alt="image" src="https://github.com/4-design/for-ui/assets/8467289/018c8815-0736-41ef-b768-a0d9dbfd9c25"> | <img width="1387" alt="image" src="https://github.com/4-design/for-ui/assets/8467289/6313d980-26e6-496e-b87a-1c8e0e2d896b"> |
| <img width="1386" alt="image" src="https://github.com/4-design/for-ui/assets/8467289/5fa4f379-2570-4fb9-8a66-ed2815f78c29"> | <img width="1386" alt="image" …

fix(Button): `intention=subtle`かつ構造がアイコンのときの色を修正

---

.changeset/forty-parents-fix.md
packages/for-ui/src/button/Button.tsx

- Close #1405 
- Buttonの中で構造を判定するのに使っている `extractText` がchildrenがnumberのときに無視していたのを修正
わかりにくいですがtextのときのpaddingが左右に広めに取られるようになっているのを確認しました
| 変更前 | 変更後 |
|    ![](https://user-images.githubusercontent.com/8467289/255100085-26c5ac87-1c8b-4205-91fd-18ef93d0ee15.png)    |     ![](https://user-images.githubusercontent.com/8467289/255100175-6a833330-dcf9-4a93-aeba-12363a3d0f48.png)   |
-

fix(Button): childrenがnumberのときも構造上テキストとして扱うよう修正

---

.changeset/great-suns-look.md
packages/for-ui/src/table/Table.stories.tsx
packages/for-ui/src/table/Table.tsx
packages/for-ui/src/table/TablePagination.test.tsx
packages/for-ui/src/table/TablePagination.tsx
packages/for-ui/src/textArea/TextArea.test.tsx
packages/for-ui/src/textField/TextField.test.tsx

- Close #1325 
- Paginationコンポーネントを新たに[デザイン](https://www.figma.com/file/FXAVXugpz9S1j3k8Lcs6au/For-UI-v1.1.9?type=design&node-id=315-9187&mode=design&t=ib5S9Jzr609PMMSN-11)に合わせて作成
- `inputtable={true}`は未実装
- TablePaginationからPaginationを使うように修正
- onChangePaginationをonChangePageに修正: Paginationはページ送りという意味なのでPageのほうが好ましい
- Tableの`disablePagination={false}`のときのデザインを更新
- 中央揃えに変更
- Pagination自体にはmargin等をもたせたくないのでそれに合わせた更新
| 変更前 | 変更後 |
|   <img width="1386" alt="image" src="https://github.com/4-design/for-ui/assets/8467289/25fcfa0b-5cf8-4b9d-bb6d-311c3e95ca87">     |    <img width="1387" alt="image" src="https://github.com/4-design/for-ui/assets/8467289/4b5149f3-8a7b-4461-a86e-f503e7daf3f4">    |
-

fix(Pagination): デザイン修正

---

.changeset/lemon-peaches-visit.md
packages/for-ui/src/table/Table.stories.tsx
packages/for-ui/src/table/Table.tsx

fix(Table): SelectRow デフォルト値設定可能にする

---

.changeset/clean-toys-taste.md
packages/for-ui/src/skeleton/Skeleton.stories.tsx
packages/for-ui/src/skeleton/Skeleton.tsx

- Close #1488
- 子要素を持たないSkeletonの場合、loading propなどなくてもSkeletonを表示するようにした
- Textと同じsize propを持つことでTextの代替としてSkeletonを出すことが簡単にできるようにした
| 変更前 | 変更後 |
-

feat(Skeleton): 子要素によって変化しないSkeletonを追加

---

.changeset/lucky-gifts-cover.md
packages/for-ui/src/table/Table.stories.tsx
packages/for-ui/src/table/Table.tsx

- Close #1499 
- `selectedRow`, `selectedRows` propはuncontrolledなpropなので `default` prefixつきに変更
| 変更前 | 変更後 |
-

fix(Table): `default` prefixを`selectedRow`, `selectedRows` に付与

---

.changeset/perfect-ties-taste.md
packages/for-ui/src/table/ColumnDef.ts
packages/for-ui/src/table/Table.stories.tsx
packages/for-ui/src/table/Table.tsx
packages/for-ui/src/table/TableCell.tsx
packages/for-ui/src/table/TablePagination.tsx

- Close #1485 
- Tableにスケルトンローディングを追加
- `loading` prop と `loadingRows` propを追加
| 変更前 | 変更後 |
|   なし     |        <img width="1408" alt="image" src="https://github.com/4-design/for-ui/assets/8467289/fce26ff9-80f2-45d1-af20-1f4bf98fee17"> |
-

feat(Table): ローディングを追加

---

.changeset/spotty-carpets-perform.md
packages/for-ui/src/button/Button.tsx
packages/for-ui/src/chip/Chip.tsx
packages/for-ui/src/chip/FullChip.tsx
packages/for-ui/src/chip/LimitedChip.tsx
packages/for-ui/src/system/componentType.ts
packages/for-ui/src/table/TableCell.tsx

- Close #1479 
- 新しく `Element` 型を定義して解決
変更なし
| 変更前 | 変更後 |
-

fix: ReactNodeを返していた部分をTypeScript 5.1<向けに修正

---

.changeset/thirty-tools-reply.md
packages/for-ui/src/menu/MenuItem.tsx

- Close #1471
- MenuItemのmin-heightをリセットするようにした
| 変更前 | 変更後 |
|   <img width="598" alt="image" src="https://github.com/4-design/for-ui/assets/8467289/919f21f4-2cad-409a-9565-9176acf033ed">     |    <img width="599" alt="image" src="https://github.com/4-design/for-ui/assets/8467289/aede984f-7913-4e0e-ba63-ac2a4b81a178">    |
-
___
bug_fix
___
- Reset the minimum height of the `MenuItem` component to ensure it displays correctly in small window sizes.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix
</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>MenuItem.tsx</strong><dd><code>Reset `MenuItem` Component's Minimum Height</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …

fix(Menu): MenuItemの高さが小さい画面で崩れるのを修正

---

.changeset/proud-bugs-stare.md
packages/for-ui/src/textField/TextField.tsx

- Close #1470 
- Mobile SafariでTextField type=dateの高さが潰れてしまうのを修正
| 変更前 | 変更後 |
|   <img width="509" alt="image" src="https://github.com/4-design/for-ui/assets/8467289/27ce2465-c7a9-4934-9aae-560b867502b8">  <img width="509" alt="image" src="https://github.com/4-design/for-ui/assets/8467289/d3d2114b-a437-41ec-9a97-493afac668ba">   |     <img width="509" alt="image" src="https://github.com/4-design/for-ui/assets/8467289/54819828-6565-44ba-9bb6-b99f07f29030">  <img width="509" alt="image" src="https://github.com/4-design/for-ui/assets/8467289/8b8d54f5-b638-4470-892b-4cc383a43824">  |
- Safariだと下の画像のようにテキストの位置がずれてしまうのだが、inputにflexをいれると今度はChrome等で表示が崩れるので一旦無視してます
___
bug_fix
___
- Fixed an issue where the height of `TextField` components with `type=date` was being crushed …

fix(TextField): Mobile SafariでTextField type=dateの高さが潰れてしまうのを修正
